before_script:
  - docker info

image: registry.uwm-nm-te-capstone.com:8083/general/maven-docker:latest

stages:
  - test
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

Unit Tests:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS install

Component Tests:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS -P test-component test
  when: on_success

Build:
  stage: build
  script:
    - mvn clean -B -T 4 package
    - docker login registry.uwm-nm-te-capstone.com:8083 --username $DOCKER_REPO_USER --password $DOCKER_REPO_PASS
    - docker build -t registry.uwm-nm-te-capstone.com:8083/$CI_PROJECT_PATH:$CI_COMMIT_SHA -t registry.uwm-nm-te-capstone.com:8083/$CI_PROJECT_PATH:latest .
    - docker push registry.uwm-nm-te-capstone.com:8083/$CI_PROJECT_PATH:$CI_COMMIT_SHA
    - docker push registry.uwm-nm-te-capstone.com:8083/$CI_PROJECT_PATH:latest
  only:
    - master
  when: on_success
  artifacts:
    paths:
      - target/*.jar

Deploy:
  stage: deploy
  script:
    - bash deploy/deploy.sh
  only:
    - master

after_script:
  - 'echo "Image SHA Tag : $CI_COMMIT_SHA"'
