version: '3'

services:
    mysql:
        image: mysql:5.7.25
        container_name: mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
            MYSQL_DATABASE: 'capstone'
